package org.highmed.dsf.bpe.start;

public interface ConstantsExampleStarters
{
	String ENV_DSF_CLIENT_CERTIFICATE_PATH = "DSF_CLIENT_CERTIFICATE_PATH";
	String ENV_DSF_CLIENT_CERTIFICATE_PASSWORD = "DSF_CLIENT_CERTIFICATE_PASSWORD";

	String TTP_FHIR_BASE_URL = "https://ttp/fhir/";
	String NAMINGSYSTEM_HIGHMED_ORGANIZATION_IDENTIFIER_VALUE_TTP = "Test_TTP";

	String MEDIC_1_FHIR_BASE_URL = "https://medic1/fhir/";
	String NAMINGSYSTEM_HIGHMED_ORGANIZATION_IDENTIFIER_VALUE_MEDIC_1 = "Test_MeDIC_1";

	String MEDIC_2_FHIR_BASE_URL = "https://medic2/fhir/";
	String NAMINGSYSTEM_HIGHMED_ORGANIZATION_IDENTIFIER_VALUE_MEDIC_2 = "Test_MeDIC_2";

	String MEDIC_3_FHIR_BASE_URL = "https://medic3/fhir/";
	String NAMINGSYSTEM_HIGHMED_ORGANIZATION_IDENTIFIER_VALUE_MEDIC_3 = "Test_MeDIC_3";
}
